### ISSUE TITLE
php warnings displayed upon user registration finalization

### ISSUE THREAD

**Issue by russelltsherman** [BurningFlipside/Registration#13]
when user follows link from registration email the following notices are displayed..

Notice: Undefined property: stdClass::$sn in /var/www/common/Auth/class.SQLPendingUser.php on line 21

Notice: Undefined property: stdClass::$sn in /var/www/common/Auth/class.SQLPendingUser.php on line 25

Notice: Undefined property: stdClass::$block in /var/www/common/Auth/class.SQLPendingUser.php on line 21

Notice: Undefined property: stdClass::$block in /var/www/common/Auth/class.SQLPendingUser.php on line 25

Notice: Undefined property: stdClass::$block in /var/www/common/Auth/class.SQLPendingUser.php on line 21

Notice: Undefined property: stdClass::$block in /var/www/common/Auth/class.SQLPendingUser.php on line 25

**Comment by pboyd04** [comment]
This should be in profiles right?

**Comment by russelltsherman** [comment]
yes it should.. i'll move it there
